import jobsJson from '../data/jobs.json';
import personalitiesJson from '../data/personalities.json';
import traitsJson from '../data/traits.json';
import enemiesJson from '../data/enemies.json';
import itemsJson from '../data/items.json';
import areasJson from '../data/areas.json';
import questsJson from '../data/quests.json';
import facilitiesJson from '../data/facilities.json';
import policiesJson from '../data/policies.json';
import eventsJson from '../data/events.json';
import dialogueJson from '../data/dialogue.json';
import misJson from '../data/misunderstandings.json';
import namesJson from '../data/names.json';
import charactersJson from '../data/characters.json';
import charEventsJson from '../data/charevents.json';
const byId = (arr) => Object.fromEntries(arr.map((x) => [x.id, x]));
export const JOBS = jobsJson;
export const PERSONALITIES = personalitiesJson;
export const TRAITS = traitsJson;
export const ENEMIES = enemiesJson;
export const ITEMS = itemsJson;
export const AREAS = areasJson;
export const QUESTS = questsJson;
export const FACILITIES = facilitiesJson;
export const POLICIES = policiesJson;
export const EVENTS = eventsJson;
export const MISUNDERSTANDINGS = misJson;
export const DIALOGUE = dialogueJson;
export const NAMES = namesJson;
export const JOB = byId(JOBS);
export const PERSONALITY = byId(PERSONALITIES);
export const TRAIT = byId(TRAITS);
export const ENEMY = byId(ENEMIES);
export const ITEM = byId(ITEMS);
export const AREA = byId(AREAS);
export const QUEST = byId(QUESTS);
export const FACILITY = byId(FACILITIES);
export const POLICY = byId(POLICIES);
export const PROTAGONIST = 'ユウト';
export const CHARACTERS = charactersJson;
export const CHAR_EVENTS = charEventsJson;
