import { writeFileSync, mkdirSync } from 'node:fs';
import { autoplay } from '../src/core/autoplay';
import { newGame } from '../src/core/game';
import { CHAPTERS } from '../src/core/story';
mkdirSync('artifacts/fixtures', { recursive:true });
const clear = autoplay(1, { maxDays:60 });
if (!clear.finalCleared) throw new Error('Fixture must reach a real drake victory');
clear.playerName = '検証'; clear.campaign!.prologueSeen = true;
clear.campaign!.seenChapters = CHAPTERS.filter(c=>c.id!=='homecoming').map(c=>c.id);
writeFileSync('artifacts/fixtures/clear.json', JSON.stringify(clear));
const legacy = newGame(42); delete legacy.campaign; legacy.playerName='旧セーブ';
writeFileSync('artifacts/fixtures/legacy.json',JSON.stringify(legacy));
const extension = newGame(42); extension.day=31; extension.playerName='継続'; extension.campaign!.prologueSeen=true;
extension.campaign!.seenChapters=CHAPTERS.filter(c=>c.id!=='extension'&&c.id!=='homecoming').map(c=>c.id);
writeFileSync('artifacts/fixtures/extension.json',JSON.stringify(extension));
const conversation = newGame(42); conversation.playerName='検証'; conversation.campaign!.prologueSeen=true;
conversation.campaign!.seenChapters=['first_desk']; conversation.seenCharEvents=['aldo_bow'];
writeFileSync('artifacts/fixtures/conversation.json',JSON.stringify(conversation));
console.log(`Real autoplay ending: day ${clear.day}, rep ${clear.rep}, ${clear.history.length} returns`);
